/*
 * Health Wallet & Digital Wallet API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HealthWalletDigitalWalletApi);
  }
}(this, function(expect, HealthWalletDigitalWalletApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HealthWalletDigitalWalletApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('apisAdminEmployeeMemberIDGet', function() {
        it('should call apisAdminEmployeeMemberIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apisAdminEmployeeMemberIDGet call and complete the assertions
          /*

          instance.apisAdminEmployeeMemberIDGet(memberID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('dataEmpireEmpireIDGet', function() {
        it('should call dataEmpireEmpireIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for dataEmpireEmpireIDGet call and complete the assertions
          /*

          instance.dataEmpireEmpireIDGet(empireID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HealthWalletDigitalWalletApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('dataFeatureMemberIDGet', function() {
        it('should call dataFeatureMemberIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for dataFeatureMemberIDGet call and complete the assertions
          /*

          instance.dataFeatureMemberIDGet(memberID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HealthWalletDigitalWalletApi.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('dataHraMemberIDGet', function() {
        it('should call dataHraMemberIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for dataHraMemberIDGet call and complete the assertions
          /*

          instance.dataHraMemberIDGet(memberID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
